### ISSUE TITLE
Demos must compile

### ISSUE THREAD

**Issue by Alexey-T** [paxtibi/paxjson#11]
check all demos, Json and http, that they compile, with cleaning lib dir- lib can have old named files, eg http.dcu

**Comment by paxtibi** [comment]
dcu? Isn't delphi?
I haven't release lib and bin folders as you suggested me.
I've removed from repository, you still see folders coming from repository?

**Comment by Alexey-T** [comment]
lib is removed, its Ok.
i suggest to test all your demos, with deleted copy of "lib" dir.

**Comment by paxtibi** [comment]
By  demo via travis ci :)
