### ISSUE TITLE
Const obj:TObject

### ISSUE THREAD

**Issue by Alexey-T** [paxtibi/paxjson#6]
“Const” is not needed here, it is n places in code

**Comment by paxtibi** [comment]
Wich const?
  
  TJSON3 = class
    function parse(source: TJSONStringType; const clz: TClass): TObject; overload;
    function stringify(const obj: TObject): TJSONStringType;
  end;           
  
  TJsonTypeHandler = class  
    function parse(AObject: TObject; Info: PPropInfo; const node: TJSONData):   boolean; virtual; abstract;  
    function stringify(AObject: TObject; Info: PPropInfo; out Res: TJSONData): boolean; virtual; abstract;  
  end;

TJSON3.stringify need const for provide a single property object to be translater. eg  :
TJSON3.stringify(aBigObjectContainer.aSingleObjectProperty);

In TJsonTypeHandler .parse we don't want to give the change to change json node object. You can extend the type handler set, but you must not change the nodes. const in fpc isn't like c++ const, but is a signal. "Don't touch" :) 

Do you agree?

**Comment by Alexey-T** [comment]
const in 'const obj:TObject' and 'const clz: TClass'

**Comment by paxtibi** [comment]
Removed :)

**Comment by paxtibi** [comment]
Done
