### ISSUE TITLE
GH descript

### ISSUE THREAD

**Issue by Alexey-T** [paxtibi/paxjson#7]
Gives class TJson, which can convert itself to/from JSON string. Based on fpJSON library from FPC. For further info, read ......(url)

**Comment by paxtibi** [comment]
I've try to improve readme.md.
Now is better?

**Comment by Alexey-T** [comment]
EN times are not ok
e.g.
This function **tries** to translate a string into instance of a class. **Uses** standard fpjson as parser of string. The parser function **uses** a registry for classes to be **instantiated** autonomous.
